# Generated by Django 6.0.7 on 2026-07-16 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_gamescore'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=64, unique=True)),
                ('map_name', models.CharField(blank=True, max_length=40)),
                ('rounds', models.IntegerField(default=0)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('parsed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemoPlayerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steamid', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('rounds', models.IntegerField(default=0)),
                ('kills', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('hs_kills', models.IntegerField(default=0)),
                ('damage', models.FloatField(default=0.0)),
                ('kast_rounds', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('opening_kills', models.IntegerField(default=0)),
                ('opening_deaths', models.IntegerField(default=0)),
                ('opening_wins', models.IntegerField(default=0)),
                ('trade_kills', models.IntegerField(default=0)),
                ('traded_deaths', models.IntegerField(default=0)),
                ('flash_assists', models.IntegerField(default=0)),
                ('enemies_flashed', models.IntegerField(default=0)),
                ('blind_time', models.FloatField(default=0.0)),
                ('clutch_attempts', models.IntegerField(default=0)),
                ('clutch_won', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tracker.parsedmatch')),
            ],
            options={
                'indexes': [models.Index(fields=['steamid'], name='tracker_dem_steamid_384acf_idx')],
                'unique_together': {('match', 'steamid')},
            },
        ),
    ]
