# Generated by Django 6.0.7 on 2026-07-24 11:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_banrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('component', models.CharField(help_text='e.g. FACEIT Data API', max_length=100)),
                ('endpoint', models.CharField(blank=True, help_text='Optional, e.g. open.faceit.com', max_length=120)),
                ('impact', models.CharField(choices=[('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical'), ('maintenance', 'Maintenance')], default='minor', max_length=20)),
                ('status', models.CharField(choices=[('investigating', 'Investigating'), ('identified', 'Identified'), ('monitoring', 'Monitoring'), ('resolved', 'Resolved')], default='investigating', max_length=20)),
                ('started', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved', models.DateTimeField(blank=True, help_text='Set when the incident is over.', null=True)),
                ('published', models.BooleanField(default=True, help_text='Untick to hide this incident from the public status page.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-started'],
            },
        ),
        migrations.CreateModel(
            name='IncidentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('investigating', 'Investigating'), ('identified', 'Identified'), ('monitoring', 'Monitoring'), ('resolved', 'Resolved')], default='investigating', max_length=20)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField()),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='tracker.incident')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
    ]
