# Generated by Django 6.0.7 on 2026-07-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.CreateModel(
            name='AllstarClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('steamid', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('match_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('status', models.CharField(blank=True, default='', max_length=20)),
                ('on_demand', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('clip_url', models.URLField(blank=True, default='', max_length=500)),
                ('thumb', models.URLField(blank=True, default='', max_length=500)),
                ('snapshot', models.URLField(blank=True, default='', max_length=500)),
                ('demo_url', models.URLField(blank=True, default='', max_length=1000)),
                ('round_number', models.IntegerField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('cs_map', models.CharField(blank=True, default='', max_length=40)),
                ('kills', models.CharField(blank=True, default='', max_length=8)),
                ('weapons', models.CharField(blank=True, default='', max_length=100)),
                ('headshots', models.CharField(blank=True, default='', max_length=8)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['steamid', 'status'], name='tracker_all_steamid_1c5f49_idx')],
            },
        ),
    ]
