# Generated by Django 6.0.7 on 2026-08-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_alter_userprofile_avatar_allstarclip'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorSalt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('salt', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PathDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('route', models.CharField(max_length=200)),
                ('hits', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-hits'],
                'unique_together': {('day', 'route')},
            },
        ),
        migrations.CreateModel(
            name='VisitorDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('visitor', models.CharField(max_length=32)),
            ],
            options={
                'indexes': [models.Index(fields=['day'], name='tracker_vis_day_299ef3_idx')],
                'unique_together': {('day', 'visitor')},
            },
        ),
    ]
