# Generated by Django 6.0.5 on 2026-09-10 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0025_changelog_reaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ban', 'Ban on a followed player')], default='ban', max_length=20)),
                ('title', models.CharField(max_length=140)),
                ('body', models.CharField(blank=True, max_length=240)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('dedupe', models.CharField(max_length=140)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read'], name='tracker_not_user_id_742549_idx')],
                'unique_together': {('user', 'dedupe')},
            },
        ),
    ]
