// CS2 buy-menu prices (approximate, well-known values).
export const WEAPONS = [
  { name: "Glock-18", price: 200 },
  { name: "USP-S", price: 200 },
  { name: "P250", price: 300 },
  { name: "Five-SeveN", price: 500 },
  { name: "Tec-9", price: 500 },
  { name: "CZ75-Auto", price: 500 },
  { name: "Desert Eagle", price: 700 },
  { name: "R8 Revolver", price: 600 },
  { name: "MAC-10", price: 1050 },
  { name: "MP9", price: 1250 },
  { name: "MP7", price: 1500 },
  { name: "UMP-45", price: 1200 },
  { name: "P90", price: 2350 },
  { name: "PP-Bizon", price: 1400 },
  { name: "Galil AR", price: 1800 },
  { name: "FAMAS", price: 2050 },
  { name: "AK-47", price: 2700 },
  { name: "M4A4", price: 3000 },
  { name: "M4A1-S", price: 2900 },
  { name: "SG 553", price: 3000 },
  { name: "AUG", price: 3300 },
  { name: "SSG 08", price: 1700 },
  { name: "AWP", price: 4750 },
  { name: "G3SG1", price: 5000 },
  { name: "SCAR-20", price: 5000 },
  { name: "Nova", price: 1050 },
  { name: "XM1014", price: 2000 },
  { name: "MAG-7", price: 1300 },
  { name: "M249", price: 5200 },
  { name: "Negev", price: 1700 },
  { name: "Kevlar Vest", price: 650 },
  { name: "Kevlar + Helmet", price: 1000 },
  { name: "Zeus x27", price: 200 },
  { name: "HE Grenade", price: 300 },
  { name: "Flashbang", price: 200 },
  { name: "Smoke Grenade", price: 300 },
  { name: "Molotov", price: 400 },
  { name: "Incendiary Grenade", price: 600 },
  { name: "Decoy Grenade", price: 50 },
];

// CS trivia / history questions. answer = index into options.
export const TRIVIA = [
  { q: "Who won the first CS:GO Major (DreamHack Winter 2013)?",
    options: ["Fnatic", "NiP", "VeryGames", "NAVI"], answer: 0 },
  { q: "Which team won the first CS2 Major (PGL Copenhagen 2024)?",
    options: ["FaZe", "Natus Vincere", "Vitality", "G2"], answer: 1 },
  { q: "How many players are on a team in standard competitive?",
    options: ["4", "5", "6", "7"], answer: 1 },
  { q: "How long until the C4 explodes after being planted?",
    options: ["35s", "40s", "45s", "30s"], answer: 1 },
  { q: "Maximum money a player can hold?",
    options: ["$12,000", "$16,000", "$20,000", "$15,000"], answer: 1 },
  { q: "How much does the AWP cost?",
    options: ["$4,750", "$5,000", "$4,500", "$4,000"], answer: 0 },
  { q: "Bomb defuse time WITHOUT a defuse kit?",
    options: ["5s", "7s", "10s", "12s"], answer: 2 },
  { q: "Bomb defuse time WITH a defuse kit?",
    options: ["3s", "5s", "7s", "8s"], answer: 1 },
  { q: "In which year did CS2 replace CS:GO?",
    options: ["2021", "2022", "2023", "2024"], answer: 2 },
  { q: "How many rounds are in one half under MR12 (CS2)?",
    options: ["10", "12", "15", "16"], answer: 1 },
  { q: "Starting money for the pistol round?",
    options: ["$600", "$800", "$1,000", "$500"], answer: 1 },
  { q: "How many bullets in an AWP magazine?",
    options: ["5", "8", "10", "12"], answer: 2 },
  { q: "Which org has won the most CS:GO Majors?",
    options: ["NAVI", "Astralis", "Fnatic", "FaZe"], answer: 1 },
  { q: "How much does a full Kevlar + Helmet cost?",
    options: ["$650", "$800", "$1,000", "$1,200"], answer: 2 },
  { q: "What is the price of an HE grenade?",
    options: ["$200", "$300", "$400", "$250"], answer: 1 },
  { q: "How much HP does a player start with (no armor damage)?",
    options: ["100", "120", "90", "150"], answer: 0 },
  { q: "The 'Deagle' refers to which weapon?",
    options: ["Dual Berettas", "Desert Eagle", "R8 Revolver", "Five-SeveN"], answer: 1 },
  { q: "How many Major MVP medals make a player legendary — who has the most?",
    options: ["device", "s1mple", "ZywOo", "NiKo"], answer: 1 },
];
