// CS2 buy-menu prices (approximate, well-known values).
//
// `icon` is the filename under /public/weapons, which follows Valve's own
// internal naming rather than the display name — so two of these look wrong
// and are not: the M4A4 is `m4a1` in the game files and the M4A1-S is
// `m4a1_silencer`, and the SG 553 ships as `sg556`. Renaming them to match
// the labels would break the mapping the next time the set is refreshed.
export const WEAPONS = [
  { name: "Glock-18", price: 200, icon: "glock" },
  { name: "USP-S", price: 200, icon: "usp_silencer" },
  { name: "P250", price: 300, icon: "p250" },
  { name: "Five-SeveN", price: 500, icon: "fiveseven" },
  { name: "Tec-9", price: 500, icon: "tec9" },
  { name: "CZ75-Auto", price: 500, icon: "cz75a" },
  { name: "Desert Eagle", price: 700, icon: "deagle" },
  { name: "R8 Revolver", price: 600, icon: "revolver" },
  { name: "MAC-10", price: 1050, icon: "mac10" },
  { name: "MP9", price: 1250, icon: "mp9" },
  { name: "MP7", price: 1500, icon: "mp7" },
  { name: "UMP-45", price: 1200, icon: "ump45" },
  { name: "P90", price: 2350, icon: "p90" },
  { name: "PP-Bizon", price: 1400, icon: "bizon" },
  { name: "Galil AR", price: 1800, icon: "galilar" },
  { name: "FAMAS", price: 2050, icon: "famas" },
  { name: "AK-47", price: 2700, icon: "ak47" },
  { name: "M4A4", price: 3000, icon: "m4a1" },
  { name: "M4A1-S", price: 2900, icon: "m4a1_silencer" },
  { name: "SG 553", price: 3000, icon: "sg556" },
  { name: "AUG", price: 3300, icon: "aug" },
  { name: "SSG 08", price: 1700, icon: "ssg08" },
  { name: "AWP", price: 4750, icon: "awp" },
  { name: "G3SG1", price: 5000, icon: "g3sg1" },
  { name: "SCAR-20", price: 5000, icon: "scar20" },
  { name: "Nova", price: 1050, icon: "nova" },
  { name: "XM1014", price: 2000, icon: "xm1014" },
  { name: "MAG-7", price: 1300, icon: "mag7" },
  { name: "M249", price: 5200, icon: "m249" },
  { name: "Negev", price: 1700, icon: "negev" },
  { name: "Kevlar Vest", price: 650, icon: "kevlar" },
  { name: "Kevlar + Helmet", price: 1000, icon: "assaultsuit" },
  { name: "Zeus x27", price: 200, icon: "taser" },
  { name: "HE Grenade", price: 300, icon: "hegrenade" },
  { name: "Flashbang", price: 200, icon: "flashbang" },
  { name: "Smoke Grenade", price: 300, icon: "smokegrenade" },
  { name: "Molotov", price: 400, icon: "molotov" },
  { name: "Incendiary Grenade", price: 600, icon: "incgrenade" },
  { name: "Decoy Grenade", price: 50, icon: "decoy" },
];

// CS trivia / history questions. answer = index into options.
export const TRIVIA = [
  { q: "Who won the first CS:GO Major (DreamHack Winter 2013)?",
    options: ["Fnatic", "NiP", "VeryGames", "NAVI"], answer: 0 },
  { q: "Which team won the first CS2 Major (PGL Copenhagen 2024)?",
    options: ["FaZe", "Natus Vincere", "Vitality", "G2"], answer: 1 },
  { q: "How many players are on a team in standard competitive?",
    options: ["4", "5", "6", "7"], answer: 1 },
  { q: "How long until the C4 explodes after being planted?",
    options: ["35s", "40s", "45s", "30s"], answer: 1 },
  { q: "Maximum money a player can hold?",
    options: ["$12,000", "$16,000", "$20,000", "$15,000"], answer: 1 },
  { q: "How much does the AWP cost?",
    options: ["$4,750", "$5,000", "$4,500", "$4,000"], answer: 0 },
  { q: "Bomb defuse time WITHOUT a defuse kit?",
    options: ["5s", "7s", "10s", "12s"], answer: 2 },
  { q: "Bomb defuse time WITH a defuse kit?",
    options: ["3s", "5s", "7s", "8s"], answer: 1 },
  { q: "In which year did CS2 replace CS:GO?",
    options: ["2021", "2022", "2023", "2024"], answer: 2 },
  { q: "How many rounds are in one half under MR12 (CS2)?",
    options: ["10", "12", "15", "16"], answer: 1 },
  { q: "Starting money for the pistol round?",
    options: ["$600", "$800", "$1,000", "$500"], answer: 1 },
  { q: "How many bullets in an AWP magazine?",
    options: ["5", "8", "10", "12"], answer: 2 },
  { q: "Which org has won the most CS:GO Majors?",
    options: ["NAVI", "Astralis", "Fnatic", "FaZe"], answer: 1 },
  { q: "How much does a full Kevlar + Helmet cost?",
    options: ["$650", "$800", "$1,000", "$1,200"], answer: 2 },
  { q: "What is the price of an HE grenade?",
    options: ["$200", "$300", "$400", "$250"], answer: 1 },
  { q: "How much HP does a player start with (no armor damage)?",
    options: ["100", "120", "90", "150"], answer: 0 },
  { q: "The 'Deagle' refers to which weapon?",
    options: ["Dual Berettas", "Desert Eagle", "R8 Revolver", "Five-SeveN"], answer: 1 },
  { q: "How many Major MVP medals make a player legendary — who has the most?",
    options: ["device", "s1mple", "ZywOo", "NiKo"], answer: 1 },
];
