// Curated CS "legends" dataset for ProGuesser (data as of ~2025).
// Fields: nickname, country {code,name}, region, role, majors (count), age.
// Chosen for well-established, stable facts so the daily puzzle stays fair.

export const PROS = [
  { nickname: "s1mple", country: { code: "ua", name: "Ukraine" }, region: "EU", role: "AWPer", majors: 1, age: 28 },
  { nickname: "ZywOo", country: { code: "fr", name: "France" }, region: "EU", role: "AWPer", majors: 0, age: 25 },
  { nickname: "NiKo", country: { code: "ba", name: "Bosnia" }, region: "EU", role: "Rifler", majors: 0, age: 28 },
  { nickname: "device", country: { code: "dk", name: "Denmark" }, region: "EU", role: "AWPer", majors: 4, age: 30 },
  { nickname: "dupreeh", country: { code: "dk", name: "Denmark" }, region: "EU", role: "Entry", majors: 4, age: 32 },
  { nickname: "Xyp9x", country: { code: "dk", name: "Denmark" }, region: "EU", role: "Support", majors: 4, age: 30 },
  { nickname: "gla1ve", country: { code: "dk", name: "Denmark" }, region: "EU", role: "IGL", majors: 2, age: 30 },
  { nickname: "Magisk", country: { code: "dk", name: "Denmark" }, region: "EU", role: "Rifler", majors: 2, age: 27 },
  { nickname: "electronic", country: { code: "ru", name: "Russia" }, region: "EU", role: "Rifler", majors: 1, age: 27 },
  { nickname: "b1t", country: { code: "ua", name: "Ukraine" }, region: "EU", role: "Rifler", majors: 1, age: 22 },
  { nickname: "Perfecto", country: { code: "ru", name: "Russia" }, region: "EU", role: "Support", majors: 1, age: 25 },
  { nickname: "sh1ro", country: { code: "ru", name: "Russia" }, region: "EU", role: "AWPer", majors: 0, age: 24 },
  { nickname: "Ax1Le", country: { code: "ru", name: "Russia" }, region: "EU", role: "Rifler", majors: 0, age: 23 },
  { nickname: "HObbit", country: { code: "kz", name: "Kazakhstan" }, region: "EU", role: "Rifler", majors: 1, age: 31 },
  { nickname: "ropz", country: { code: "ee", name: "Estonia" }, region: "EU", role: "Lurker", majors: 1, age: 25 },
  { nickname: "karrigan", country: { code: "dk", name: "Denmark" }, region: "EU", role: "IGL", majors: 1, age: 35 },
  { nickname: "rain", country: { code: "no", name: "Norway" }, region: "EU", role: "Entry", majors: 1, age: 31 },
  { nickname: "broky", country: { code: "lv", name: "Latvia" }, region: "EU", role: "AWPer", majors: 1, age: 25 },
  { nickname: "Twistzz", country: { code: "ca", name: "Canada" }, region: "NA", role: "Rifler", majors: 1, age: 26 },
  { nickname: "NAF", country: { code: "ca", name: "Canada" }, region: "NA", role: "Rifler", majors: 0, age: 27 },
  { nickname: "EliGE", country: { code: "us", name: "USA" }, region: "NA", role: "Entry", majors: 0, age: 28 },
  { nickname: "Stewie2K", country: { code: "us", name: "USA" }, region: "NA", role: "IGL", majors: 1, age: 27 },
  { nickname: "autimatic", country: { code: "us", name: "USA" }, region: "NA", role: "Rifler", majors: 1, age: 28 },
  { nickname: "FalleN", country: { code: "br", name: "Brazil" }, region: "SA", role: "AWPer", majors: 2, age: 34 },
  { nickname: "coldzera", country: { code: "br", name: "Brazil" }, region: "SA", role: "Rifler", majors: 2, age: 30 },
  { nickname: "fer", country: { code: "br", name: "Brazil" }, region: "SA", role: "Entry", majors: 2, age: 32 },
  { nickname: "TACO", country: { code: "br", name: "Brazil" }, region: "SA", role: "Support", majors: 2, age: 30 },
  { nickname: "m0NESY", country: { code: "ru", name: "Russia" }, region: "EU", role: "AWPer", majors: 0, age: 20 },
  { nickname: "donk", country: { code: "ru", name: "Russia" }, region: "EU", role: "Rifler", majors: 0, age: 18 },
  { nickname: "huNter-", country: { code: "ba", name: "Bosnia" }, region: "EU", role: "Rifler", majors: 0, age: 29 },
  { nickname: "frozen", country: { code: "sk", name: "Slovakia" }, region: "EU", role: "Rifler", majors: 0, age: 24 },
  { nickname: "blameF", country: { code: "dk", name: "Denmark" }, region: "EU", role: "Rifler", majors: 0, age: 27 },
  { nickname: "jks", country: { code: "au", name: "Australia" }, region: "OCE", role: "Rifler", majors: 0, age: 30 },
  { nickname: "flusha", country: { code: "se", name: "Sweden" }, region: "EU", role: "Rifler", majors: 3, age: 30 },
  { nickname: "JW", country: { code: "se", name: "Sweden" }, region: "EU", role: "AWPer", majors: 2, age: 30 },
  { nickname: "KRIMZ", country: { code: "se", name: "Sweden" }, region: "EU", role: "Support", majors: 2, age: 30 },
  { nickname: "olofmeister", country: { code: "se", name: "Sweden" }, region: "EU", role: "Rifler", majors: 2, age: 33 },
  { nickname: "f0rest", country: { code: "se", name: "Sweden" }, region: "EU", role: "Rifler", majors: 0, age: 37 },
  { nickname: "GeT_RiGhT", country: { code: "se", name: "Sweden" }, region: "EU", role: "Lurker", majors: 0, age: 35 },
  { nickname: "chrisJ", country: { code: "nl", name: "Netherlands" }, region: "EU", role: "AWPer", majors: 0, age: 31 },
];
